controller_list:
  - name: fake_ur10_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_robotiq_controller
    joints:
      - robotiq_85_left_knuckle_joint
      - robotiq_85_right_knuckle_joint